# network/computer sensors and scripts

wake_on_lan:

## network binary sensors
binary_sensor:
  - name: internet_connection
    platform: ping
    host: 8.8.8.8 # ping google to check
    count: 2
    scan_interval: 30
