# Light Soft UI theme inspired by @N-l1 here https://github.com/N-l1/home-assistant-config
# Theme based on "Google light theme" by Juan - @juanmtech
# Modified by @DrJohnT to implement Soft UI theme inspired by @N-l1
#
# The idea of this theme is to simply avoid repeated definitions of the same
# modifications to standard UI elements by embedding them in the theme

Soft_UI:
  # Background
  #lovelace-background: center / cover no-repeat url("/local/bg3.jpg") fixed
  #lovelace-background: radial-gradient(at 50% 50%, rgb(31, 31, 40) 0%, rgb(78, 123, 250) 100%)
  # Header:
  app-header-background-color: "#F8F8F8"
  app-header-text-color: "#424242"
  # Main Interface Colors
  primary-color: "#5F9BEA"
  light-primary-color: var(--primary-color)
  primary-background-color: "#F8F8F8"
  secondary-background-color: var(--primary-background-color)
  divider-color: var(--primary-background-color)
  # Text
  primary-text-color: "#424242"
  secondary-text-color: "#5F6267"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#717171"
  # Sidebar Menu
  sidebar-icon-color: var(--app-header-text-color)
  sidebar-text-color: "#424242"
  sidebar-background-color: "#FFFFFF"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#5F9BEA"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color))
  # States and Badges
  state-icon-color: "#5F6267"
  state-icon-active-color: "#5F9BEA"
  state-icon-unavailable-color: var(--disabled-text-color)
  # Sliders
  paper-slider-knob-color: "#5F9BEA"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)
  # Labels
  label-badge-background-color: "#F8FAF9"
  label-badge-text-color: "#4D5575"
  label-badge-red: "#C7484C"
  label-badge-green: "#6DC071"
  label-badge-blue: "#51AAD1"
  label-badge-yellow: "#D9B757"
  label-badge-gray: "#5F6267"
  # Cards
  ha-card-border-radius: "15px"
  ha-card-box-shadow: -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
  paper-card-background-color: "#FFFFFF"
  paper-listbox-background-color: "#FFFFFF"
  # Switches
  switch-checked-button-color: "#5F9BEA"
  switch-checked-track-color: "#75a2f0"
  switch-unchecked-button-color: "#5F6267"
  switch-unchecked-track-color: "#888b91"
  # Toggles
  paper-toggle-button-checked-button-color: var(--switch-checked-button-color)
  paper-toggle-button-checked-bar-color: var(--switch-checked-track-color)
  paper-toggle-button-unchecked-button-color: var(--switch-unchecked-button-color)
  paper-toggle-button-unchecked-bar-color: var(--switch-unchecked-track-color)
  # Table
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)
  data-table-background-color: var(--primary-background-color)
