# camera:
#   - platform: onvif
#     name: Living Room Camera
#     host: http://192.168.10.221:2020/onvif/device_service
#     port: 2020
#     username: !secret camera_living_room_username
#     password: !secret camera_living_room_password
  # - platform: mjpeg
  #   name: Parent Bedroom Camera
  #   still_image_url: http://192.168.89.222/image/jpeg.cgi
  #   mjpeg_url: http://192.168.89.222/video/mjpg.cgi
  #   username: !secret camera_parent_bedroom_username
  #   password: !secret camera_parent_bedroom_password
  # - platform: mjpeg
  #   name: Kitchen Camera
  #   still_image_url: http://192.168.144.24/image/jpeg.cgi
  #   mjpeg_url: http://192.168.144.24/video/mjpg.cgi
  #   username: !secret camera_kitchen_username
  #   password: !secret camera_kitchen_password
