input_number:
  bl_master_bedroom_left_blind_position:
    min: 0 # (blind is down) (cover closed)
    max: 100 # (blind is not put down) (cover open)
  bl_master_bedroom_right_blind_position:
    min: 0
    max: 100
  ifttt_ziptrak_position:
    min: 0
    max: 100

script:
  master_bedroom_left_blind_cover_open:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.bl_master_bedroom_left_blind_position
          value: 100
      - service: remote.send_command
        target:
          entity_id: remote.living_room_rm3_pro
        data:
          command: "b64:sgiwBAsYDBcYDAwXDBgLGBcMDBgMFwwXGAABFpsxDBcMFwwYFwwMFxgLDRcMGAsYDBcYDBcMDBcYCwwYDBgMFwwXDBgLGAwXGAwLGBgMDBcMFwwYDBcMFwwYDBcXDQwXDBcMGBcMDBcMGAwXGAABF5oxCxgMFwwYFwwMFxgMCxgMGAwXDBgXDBcMDBcYDAwXDBgMFwwYCxgMFwwXGAwMFxgMDBcMFwwYDBcMGAsYDBcYDAwXDBgMFxcMDBcNFwwXGAABF5oxDBcMFwwYFwwMFxgMCxgMGAwXDBcYDBcMDBgXDAwXDBgMFwwYDBcMFwwYFwwMFxgMDBcMGAsYDBcMGAwXDBcYDAwYCxgMFxgMCxgMFwwYFwABHpswDBcMGAwXGAsMGBcMDBcMGAwXDBgXDBgLDBgXDAwXDBgMFwwXDBgMFwwYFwwMFxcNDBgLGAsYDBcMFwwYCxgXDQwXDBgLGBcMDBcMGAsYFwABGZoxCxgMFwwXGAwMFxcMDBgMGAsYDBcYCxgMCxgYDAsYDBcMGAwXDBcMGAwXFwwMGBcNCxgMFwwYCxgMFwwYCxgXDQsYDBcMGBcMDBcMGAsYFwABGJoxCxgMFwwYFwwMFxcMDBgMGAsYDBcYCxgMDBcXDAwYDBgLGAwXDBgLGAwXGAsMGBcNCxgMFwwYCxgLGAwXDBgXDAwYDBcMGBcMDBcMFwwYFwABF5oxDBgLGAsYGAsMGBcMDBcMGAwXDBgXDBcMDBgXDAwXDBgMFwwYDBcMFwwYFwwMFxgMDBcMGAwXDBcMGAwXDBcYDAwYCxgMFxgMCxgMFwwYFwABF5oxDBcMFwwYFwwMFxgMDBcMGAwXDBgXDBcMDBgXDAwXDBgMFwwXDBgMFwwYFwwMFxgMDBcMGAwXDBcMGAwXDBcYDAwXDBgLGBcMDBgMFwwXGAABF5oxCxgMFwwXGAwMFxcMDBgLGAwYCxgXDBgMCxgXDAwYCxgMGAsYDBgLGAwXGAsMGBcMDBgLGAwYCxgLGAwYCxgXDQsYDBcMFxgMDBcMFwwYFwABF5swDBgMFwwXGAwLGBcMDBgMFwwYCxgYCxgMCxgYCwwYCxgMGAwXDBgLGAwXGAwLGBcNCxgMFwwXDBgMFwwXDBgXDQsYDBcMGBcMDBcMGAsYFwABF5swDBgMFwwYFwwMFxcMDBgLGQsYDBcYCxgMDBcXDAwYDBgLGAwXDBcMGAwXGAsMGBcNCxgMFwwYCxgMFwwXDBgXDQwXDBgLGBcMDBcMGAsYFwABIpswDBgLGAwXFw0LGBcMDBcMGAwXDBgXDBcMDBgXDAwXDBgMFwwYCxgMFwwXGAwMFxgMDBcMGAsYDBcMGAsYCxgYDAwXDBcMGBcMDBcMGAwXFwABDpswDBgLGAwXGAwLGBcMDBcMGAwXDBgXDBgLDBgXDAwXDBgMFwwYDBcMFwwYFwwMFxgMDBcMGAwXDBcMGAsYDBcYDAwXDBgLGBgLDBgMFwwXGAABDZswDBgMFwwXGAsNFxgLDBcNFwwYDBcXDRcMCxgXDAwXDBgMFw0XDBcMFwwYFwwMFxgMDBcMGAwXDBcMGAwXDBcYDAwXDBgMFxcMDBgMFwwXGAAF3AAAAAAAAAAA"
  master_bedroom_left_blind_cover_close:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.bl_master_bedroom_left_blind_position
          value: 0
      - service: remote.send_command
        target:
          entity_id: remote.living_room_rm3_pro
        data:
          command: "b64:sguwBAwXDBcYDAwYCxgXDBgMCxgMFxgMFwABF5oxDBcMGAwXFwwMGBcMDBcMGAwXDBgXDBgLDBcYDAwXDBgMFwwYDBcMGAsYFwwMFxgMDBcMGAwXDBgLGAwXDBcYDAwXDBgXDBgLDBgMFxgMFwABE5owDBgMFwwYFwwMFxgMCxgMGAsYDBcYCxgMDBcYCwwYDBcMGAwXDBcMGAwXGAsMGBcNCxgMFwwXDBgMFwwXDBgXDAwYDBcYDBcMDBcMFxgMFwABF5swDBgMFwwXGAwLGBcMDBgLGQsYDBcXDBgLDRcXDAwYDBcMGAsYDBcMGAwXGAsMFxgNCxgMFwwXDBgMFwwXDBgXDQsYDBcYDBcMCxgMFxgMFwABF5oxDBcMGAsYFwwMGBcMDBcMGAwXDBgXDBcMDBgXDAwXDBgMFwwXDBgMFwwYFwwMFxgMDBcMGAwXDBcMGAwXDBcXDQwXDBgXDBcMDBgMFxcMFwABI5swDBcMGAwXFwwMGBcMDBcMGAwXDBgXDBcMDBgXDAwXDBgMFwwXDBgMFwwXGAwLGBgMCxgMFwwYCxgMFwwYDBcXDQwXDBcYCxgMDBcMGBcMFwABGJswDBgLGAwXGAsMGBcMDBcMGAwXDBgXDBcMDBgXDAwXDBgMGAsYDBcMGAsYFwwMFxgMDBgMFwwXDBgLGAwXDBcYDAwXDRcXDBgLDBgMFxgLGAABF5owDBgMFwwYFwwMGBcMDBcMGAwXDBcYDBcMDBgXDAsYDBgMFwwXDBgLGAwXGAwMFxcNDBcMGAsYDBcMFwwYDBcYDAwXDBgXDBcMDBcMGBcMGAABFpswDBgMFwwXGAwLGBcMDBgLGAwYDBcYCxgMDBcXDAwYCxgMGAwXDBcMGAwXFwwMFxgMDBgMFwwXDBgMFwwXDBgXDAwYDBcYCxgLDRcMFxgMFwABF5oxDBcMFwwYFwwMFxgMDBcMGAwXDBcYDBcMDBcYDAsYDBgMFwwXDBgLGAwXGAwLGBcNDBcMFwwYDBcMFwwYDBcXDQwXDBgXDBcMDBcMGBcMGAABF5owDBgLGAwXGAwMFxcMDBcMGAwYDBcYCxgMCxgXDAwXDBgMFw0XDBcMGAwXFwwMFxgMDBcNFwwXDBgMFwwXDBgXDAwYDBcYCxgMDBcMFxgMFwABE5owDRcMFwwYFwwMFxgLDBgMGAwXDBcYDBcMDBcYDAsYDBgMFwwXDBgMFwwXGAsNFxgMDBcMFwwYCxgMGAsYCxgYDAwXDBgXDBcMDBgLGBcMGAABFpswDBgLGAwXGAwLGBcMDBgLGAwYDBcYCxgLDRcYDAsYCxgMGAwXDBcMGAsYGAsMGBcMDBgMFwwXDBgMFwwXDBgXDAwYDBcYDBcMDBcMFxgMFwABDZswDBgMFwwXGAwLGBcMDBcMGAwYDBcYCxgLDBgXDAwYCxgMGAsYDBcMGAwXGAsMGBcMDBgLGAwXDBcNFwwXDBgXDAwYDBcXDBgMDBcMFxgLGAABFZswDBcMGAwXFwwMGBcMDBcMGAwXDBgXDBgLDBgXDAwXDBgMFwwYCxgMFwwXGAwMFxgMDBcMFwwYDBcMFwwYDBcYDAwXDBcYCxgMDBcNFhgMFwAF3AAAAAAAAAAA"
  master_bedroom_left_blind_cover_stop:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.bl_master_bedroom_left_blind_position
          value: 50
      - service: remote.send_command
        target:
          entity_id: remote.living_room_rm3_pro
        data:
          command: "b64:sgD8AJoxDBcMFw0XFwwMFxgLDRcMFw0WDRcYDBcLDRcYCw0XDBcNFwwXDBcNFwwXGAsNFxgLDRcMFwwXDRcMFwwXDRcYCw0XGAsMFxgMDBcYCwwYFwABE5swDBcMFw0XGAsMFxgMDBcMGAwXDBcYDBcMDBcYCw0XDBgMFwwXDRcMFwwXGAsNFxgMDBcMFwwYDBcMFw0XDBcYDAwXGAsMFxgMDBcYCw0XGAABE5swDBcMFw0XGAsMFxgMDBcMGAwXDBcYDBcMDBcYDAwXDBgMFwwXDBcNFwwXGAsNFxgMDBcMFw0XDBcMFw0XDBcYCw0XGAsMGBcMDBcYCw0XGAAF3AAAAAAAAAAAAAAAAA=="
  master_bedroom_right_blind_cover_open:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.bl_master_bedroom_right_blind_position
          value: 100
      - service: remote.send_command
        target:
          entity_id: remote.living_room_rm3_pro
        data:
          command: "b64:sgiwBAwYFwwMGAwXDBcMGBcMDBcMGAwXGAABFpswDBgMFwwXGAwMFxgLDBcMGQsYDBcYCxgMDBcYCwwXDRcMGAwXDBcMGAwXGAsMFxgMDBgMFwwXDBcNFwwXGAwMGAwXDBcMGBcMDBcMFw0XFwABE5oxDBcMFw0XFwwMGBcMDBcMGAwXDBcYDBcMDBcYDAwXDBgMFwwXDBcNFwwXGAsNFxgMDBcMFwwYDBcMFwwYFwwMGAwXDBcNFxgLDBcNFwwXGAABFpsxDBcMFwwYFwwMFxgLDRcMFw0XDBcYDBgLDBcYCw0XDBgMFwwXDBgMFwwXGAwMFxgMDBcMFwwYDBcMFwwYFwwMGAwXDBgMFxcMDBcNFwwXGAABF5oxCxgMFwwXGAwMFxgLDBgMFw0XDBcYCxgMDBgXCw0XDBgLGAwXDBcMGAwXGAwLGBcMDRcMFwwYDBcMFwwXGAwMGAwXDBcMGBcMDBcMGAwXGAABIpswDBcMGAwXGAsMFxgMDBcMGAwXDBgXDBcMDBcYDAwXDBgMFwwXDBgMFwwXGAwMFxgMDBcMFwwYDBcMFwwYFwwMGAwXDBcMGBcMDBcMGAwXGAABF5swDBgMFwwXGAsNFxcMDBgMFwwXDRcYCxgLDRcYCwwXDBgMFw0XDBcMGAwXFwwMFxgMDBgMFwwXDBcNFwwXGAsMGAwYDBcMFxgMDBcMFwwYFwABF5swDBcMFwwYFwwMFxgMDBcMGAwXDBgXDBcMDBcYDAwXDBgMFwwXDBgMFwwXGAwMFxgMDBcMFwwYDBcMGAsYFwwMGAwXDBcMGBcMDBcMGAwXGAABFpswDBcNFwwXGAwMFxgLDBgMFwwYDBcYCxgMDBcYCwwYDBcMGAwXDBcNFwwXGAsMGBcMDRcMFwwYCxgMFwwYFwwMFw0XDBcMGBcMDBcMFw0XFwABF5swDBcMGAwXGAsMGBcMDBcMGAwXDBgXDBgLDBgXDAwXDBgMFw0XDBcMFwwYGAsMFxgMDBcMGAwXDBgLGAwXGAsMGAwXDBgMFxgLDRcMFwwXGAABF5oxDBcMFwwYFwwMFxgLDRcMGAwXDBcYDBcMDBcYDAwXDBgMFwwXDBgMFwwXGAwMFxgLDRcMFwwYDBcMFwwYFwwMGAwXDBcMGBcMDBcMGAwXGAABEpswDBcMGAwXGAsMGBcMDBcMGAwXDRcXDBgLDBcYDAwXDBgMFwwYDBcMFwwYFwwMFxgMDBcMGAwXDBcMGAwXGAsMGAwYCxgMFxgLDBgMFwwXGAABFpsxDBcMFwwYFwwMFxgLDRcMGAwXDBcYDBcMDBcYDAwXDBgMFwwYCxgMFwwYFwwMFxgMDBcMFwwYDBcMGAsYFwwMGAwXDBgLGBcMDBcMGAwXGAABDJswDRcMFwwXGAwMFxgLDBgMFwwYDBcYCxgMDBcYCwwXDRcMGAwXDBcMGAwXGAsMFxgMDBgMFwwXDBgMFwwXGAwMFwwYDBcMFxgMDBcMGAsYFwABFZswDBcMGAwXFwwMGBcMDBcMGAwXDBgXDBcMDBcYCw0XDBgMFwwXDBcNFwwXGAwLGBcMDBgMFwwXDBgMFwwXGAwMFwwYDBcMFxgMDBcMFwwYFwAF3AAAAAAAAAAA"
  master_bedroom_right_blind_cover_close:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.bl_master_bedroom_right_blind_position
          value: 0
      - service: remote.send_command
        target:
          entity_id: remote.living_room_rm3_pro
        data:
          command: "b64:sg2wBAwXGAwMGAwXDBcYCxgMDBcMFxgMFwABGJswDBcMFwwYGAsMFxgMDBcMGAwXDBgXDBgLDBcYCw0XDBgMFwwYDBcMFwwXGAwMFxgMDBcNFwwXDBcMGAwXGAsMGAwXDBgXDBgLDBgMFxgLGAABIpswDRcMFwwXGAsNFxgLDBcNFwwYDBcYCxgLDBgXDAwXDBgMFw0XDBcMFw0XFwwMFxgMDBcMGAwXDBcNFwwXGAsMGAwXDRYYDBgLDBcNFxcMGAABGJoxDBcMGAwXFwwMFxgMDBcMGAwXDRcXDBcMDBcYDAwXDBgMFw0WDRcMFwwYFwwMFxgMDBcNFwwXDBgMFwwXGAwMFwwYDBcXDBgMDBcMFxgLGAABF5oxDBcMFw0XFwwMFxgLDRcMGAwXDBcYDBcMDBcYCw0XDBcNFwwXDBcNFwwXGAwMFxgMDBcMFwwYDBcMFwwYFwwMGAwXDBcYDBcMDBcMGBcMGAABF5owDBgMFwwXGAwMFxgLDBcNFw0WDRcYCxgMDBcYCwwYDBcMFw0XDBcNFwwXGAsMGBcMDBgMFwwXDRcMFwwXGAwMGAwXDBcYCxgMDBcMFxgMFwABF5swDBcNFg0XGAsMGBcMDBcMGAwXDBgYCxgLDRcXDAwXDBgMFwwYDBcMFwwXGAwMFxgMDBcMGAwXDBcMGAwXGAsMGAwXDBgXDBgLDRYNFxgLGAABFpswDRcMFw0XFwwMFxgLDRcMGAwXDBcYDBcMDBcYDAwXDBgMFwwXDRcMFwwYFwwMFxgMDBcMFw0XDBcMFw0XFwwMGAwXDBgXDBgLDBgMFxgLGAABEpswDRcMFwwXGAwMFxgLDBgMGAwXDBcYDBcMDBcYCw0XDBgMFwwXDRcMFwwXGAwMFxgMDBcMFwwYDBcMFwwYFwwMGAwXDBcYDBcMDBcNFxgLGAABFpsxDBcMFwwXGAwMFxgLDBgMGAwXDBcYDBcMDBcYCw0XDBgMFwwXDRYNFwwXGAwMFxgMDBcMFwwYDBcMFwwYFwwMGAwXDBcYDBcMDBcNFxcMGAABFpswDRcMFwwXGAwMFxgLDRcMFw0XDBcYCxgLDRcYCw0XDBgMFwwXDRYNFwwXGAsNFxgMDBcMFwwXDRcMFwwYFwwMGAwXDBgXDBcMDBgMFxcMGAABIpswDBcNFwwXGAsNFhgMDBcMGAwXDBcYDBgLDBcYDAwXDBgMFwwYDBcMFw0XFwwMFxgMDBcMFw0XDBcMFw0XGAsMGAwXDRcXDBgLDBcNFxgLGAABGJowDRcMFw0XGAsMFxgMDBcMGAwXDBgXDBcMDBgXDAwXDBgMFwwXDRcMFwwYGAsMFxgMDBcMFw0XDBcNFg0XGAsNFwwXDRcXDBgLDBgMFxgLGAABDZswDBcNFg0XGAsMFxgMDBcMGAwXDRYZCxgMDBYZCwwXDBgMFw0WDRcMFw0XGAsMGBcMDRcMFwwXDBcNFwwXGAsNFwwYDBcYCxgMDBcMFxgMFwABDpswDBcNFwwXGAsMGBcMDBcMGAwXDBcZCxgLDRYYDAwXDBgMFwwYDBcMFwwYFwwMFxgMDBcMGAwXDBcMFw0XGAsMGAwXDRcYCxgLDRYNFxgLGAAF3AAAAAAAAAAA"
  master_bedroom_right_blind_cover_stop:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.bl_master_bedroom_right_blind_position
          value: 50
      - service: remote.send_command
        target:
          entity_id: remote.living_room_rm3_pro
        data:
          command: "b64:sgBQAZswDRYNFwwXGAsNFxgLDBgMFw0XDBcYCxgMDBcYCwwYDBcMGAwXDBcMGAwXGAsNFxcMDRcMFwwXDRcMFwwXGAwMGAwXGAsMFxgMDBcYCwwYFwABE5swDBgMFwwXGAsNFxcMDBcNFwwXDRcYCxgLDRcYCwwXDRcMFw0XDBcMGAwXGAsMGBcMDBgMFwwXDBcNFwwXGAwMFw0XFwwMGBcMDBcYDAwXFwABE5swDBgMFwwXGAwMFxgLDRcMFw0XDBcYCxgMDBcYCw0XDBgMFwwXDBgMFg0XGAwMFxgMDBcMFwwYDBcMFwwYFwwMGAwXGAsNFxcMDBcYDAwXGAABHpswDBcNFg0XGAsMGBcMDBcMGAwXDBgXDBgLDBgXDAwXDBgMFwwYDBcMFwwYFwwMFxgMDBcMGAwXDBcMGAwXGAsMGAwXGAwMFxgLDBgYCwwXGAAF3AAAAAAAAAAA"


  ziptrak_cover_open:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.ifttt_ziptrak_position
          value: 100
      - service: ifttt.trigger
        data:
          event: blind_up_or_at_home_mode
  ziptrak_cover_close:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.ifttt_ziptrak_position
          value: 0
      - service: ifttt.trigger
        data:
          event: blind_down_or_away_mode
  ziptrak_cover_sun_protection:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.ifttt_ziptrak_position
          value: 20
      - service: ifttt.trigger
        data:
          event: blind_down_or_away_mode

cover:
  - platform: template
    covers:
      master_bedroom_left_blind:
        device_class: blind
        friendly_name: "Master Bedroom Left Blind"
        position_template: "{{ states('input_number.bl_master_bedroom_left_blind_position') | int }}"
        open_cover:
          service: script.master_bedroom_left_blind_cover_open
        close_cover:
          service: script.master_bedroom_left_blind_cover_close
        stop_cover:
          service: script.master_bedroom_left_blind_cover_stop
        set_cover_tilt_position:
          service: script.master_bedroom_left_blind_cover_stop
  - platform: template
    covers:
      master_bedroom_right_blind:
        device_class: blind
        friendly_name: "Master Bedroom Right Blind"
        position_template: "{{ states('input_number.bl_master_bedroom_right_blind_position') | int }}"
        open_cover:
          service: script.master_bedroom_right_blind_cover_open
        close_cover:
          service: script.master_bedroom_right_blind_cover_close
        stop_cover:
          service: script.master_bedroom_right_blind_cover_stop
        set_cover_tilt_position:
          service: script.master_bedroom_right_blind_cover_stop

  - platform: group
    name: master bedroom blinds
    entities:
      - cover.master_bedroom_left_blind
      - cover.master_bedroom_right_blind
      
  - platform: template
    covers:
      ziptrak_balcony_blind:
        device_class: shade
        friendly_name: "Balcony Blind"
        position_template: "{{ states('input_number.ifttt_ziptrak_position') | int }}"
        open_cover:
          service: script.ziptrak_cover_open
        close_cover:
          service: script.ziptrak_cover_close
        stop_cover:
          service: script.ziptrak_cover_sun_protection

