# https://www.home-assistant.io/integration/switch/

input_boolean:
  bl_bedroom_ceiling_light_switch_power:

switch:
  - platform: template
    switches:
      bl_bedroom_ceiling_light_switch:
        value_template: "{{ states('input_boolean.bl_bedroom_ceiling_light_switch_power') }}"
        turn_on:
          - service: ifttt.trigger
            data:
              event: bedroom_switch_on
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.bl_bedroom_ceiling_light_switch_power
        turn_off:
          - service: ifttt.trigger
            data:
              event: bedroom_switch_off
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.bl_bedroom_ceiling_light_switch_power

light:
  - platform: switch
    name: Bedroom Ceiling Light
    entity_id: switch.bl_bedroom_ceiling_light_switch
