# # https://www.home-assistant.io/integration/switch/
# switch:
#   - platform: template
#     switches:
#       bedroom_wireless_left:
#         value_template: "{{ is_state('binary_sensor.wall_switch_left_158d00049dec5d', 'on') }}"
#         turn_on:
#           - service: automation.trigger
#             data:
#               entity_id: automation.xiaomi_switch_left
#         turn_off:
#           - service: automation.trigger
#             data:
#               entity_id: automation.xiaomi_switch_left
#       bedroom_wireless_right:
#         value_template: "{{ is_state('binary_sensor.wall_switch_left_158d00049dec5d', 'on') }}"
#         turn_on:
#           - service: ifttt.trigger
#             data:
#               event: bedroom_switch_on
#         turn_off:
#           - service: ifttt.trigger
#             data:
#               event: bedroom_switch_off
