#default: debug
logs:
  homeassistant.core: error
  homeassistant.config_entries: error
  homeassistant.components.automation: warn
  homeassistant.components.binary_sensor: error
  homeassistant.components.device_tracker: error
  homeassistant.components.discovery: warn
  homeassistant.components.feedreader: error
  homeassistant.components.http: warn
  homeassistant.components.ipp: critical
  homeassistant.components.media_player: info
  homeassistant.components.rest.sensor: critical
  homeassistant.components.recorder: error
  homeassistant.components.sensor.rest: debug
  homeassistant.components.tplink.switch: error
  homeassistant.components.zwave: warn
  homeassistant.exceptions: info
  homeassistant.helpers.script: info
  homeassistant.helpers.entity: critical
  homeassistant.loader: warn
  urllib3.connectionpool: error
  requests.packages.urllib3.connectionpool: critical
  root: warn
